name = "gude-h5"
compatibility_date = "2025-08-18"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = ".vercel/output/static"
main=".open-next/worker.js"
