name = "gude-h5"
compatibility_date = "2025-08-18"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = ".vercel/output/static"
main=".open-next/worker.js"

[env.production.vars]
NEXT_PUBLIC_API_URL = "https://gude-api.metoo.ink"
NEXT_PUBLIC_APP_NAME = "Gude"